### ISSUE TITLE
Some Build Error

### ISSUE THREAD

**Issue by minho3** [yowlings/wit_node#1]
Hello,
I have two kinds of problems

1. 
catkin_ws/src/wit_node/include/ecl/containers/array/../stencil/../common/formatters.hpp:126:114: error: expression cannot be used as a function
         FloatContainerFormatter& operator()(const unsigned int p, const int w) { format.precision(p); prm_width(w); return *this; } // Permanent

2.
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp:56:56: error: ‘SE3Group’ does not name a type
 std::ostream & operator << ( std::ostream & out, const SE3Group<T> & se3 )
                                                        ^~~~~~~~
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp:56:64: error: expected ‘,’ or ‘...’ before ‘<’ token
 std::ostream & operator << ( std::ostream & out, const SE3Group<T> & se3 )
                                                                ^
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp: In function ‘std::ostream& Sophus::operator<<(std::ostream&, int)’:
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp:60:36: error: ‘se3’ was not declared in this scope
   const Eigen::Matrix<T,3,1> & t = se3.translation();
                                    ^~~
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp: At global scope:
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp:67:56: error: ‘SE2Group’ does not name a type
 std::ostream & operator << ( std::ostream & out, const SE2Group<T> & se2 )
                                                        ^~~~~~~~
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp:67:64: error: expected ‘,’ or ‘...’ before ‘<’ token
 std::ostream & operator << ( std::ostream & out, const SE2Group<T> & se2 )
                                                                ^
catkin_ws/src/wit_node/include/ecl/linear_algebra/sophus/helpers.hpp:67:16: error: redefinition of ‘template<class T> std::ostream& Sophus::operator<<(std::ostream&, int)’
 std::ostream & operator << ( std::ostream & out, const SE2Group<T> & se2 )
                                                                   
How to fix these error?
Regards,

**Comment by yowlings** [comment]
sorry for so long time to respose.
this package is tested pass in Ubuntu18.04 ROS Melodic, please try again.
