### ISSUE TITLE
wit_node not publishing

### ISSUE THREAD

**Issue by smart-patrick** [yowlings/wit_node#2]
I successfully installed the package and launched it as described in the ros wiki page. 
However, I got the messages bellow:

[ERROR] [1603256630.811635719]: Wit : initialisation failed [/wit].
[ERROR] [1603256630.811663470]: Wit : could not initialise! Please restart.

Further, when I check the topics, nothing is published inside.

How should I proceed please?

**Comment by ryudolf** [comment]
hi, do you solve the problem? I have a same issue.

**Comment by smart-patrick** [comment]
Yeah, it is possible to deal with the errors by granting port access permission with the bellow command:
$ sudo chown %your username% /dev/wit(the port name you give)

Concerning the reason why messages aren't published in the topics, I don't know yet.

**Comment by yowlings** [comment]
The launch file use /dev/ttyUSB0 as the dev port, you can check it is correct port.
if you use /dev/ttyUSB*, there maybe not problem with the permission of port.
you can try again, if not work too, maybe you have to setting the module use the company's software in windows.
sorry for so long not response and good luck!

**Comment by xkevincode** [comment]
> Yeah, it is possible to deal with the errors by granting port access permission with the bellow command:
> $ sudo chown %your username% /dev/wit(the port name you give)
> 
> Concerning the reason why messages aren't published in the topics, I don't know yet.

Hi, I have the same issue. The launch file and wit node is running. You can see the topics by rostopic list. But no message is published in the topics.

**Comment by xkevincode** [comment]
> Yeah, it is possible to deal with the errors by granting port access permission with the bellow command:
> $ sudo chown %your username% /dev/wit(the port name you give)
> 
> Concerning the reason why messages aren't published in the topics, I don't know yet.



> The launch file use /dev/ttyUSB0 as the dev port, you can check it is correct port.
> if you use /dev/ttyUSB*, there maybe not problem with the permission of port.
> you can try again, if not work too, maybe you have to setting the module use the company's software in windows.
> sorry for so long not response and good luck!

Hi, I found one reason, and it may be reasonable. The baudrate in the cpp file is 115200 in default. There are three cases, one in "initialization" and another two in the "driver" file with 115200_baudrate. Make sure your sensor is the same or change the code to your setup and catkin_make the code again.

**Comment by kim-xps12** [comment]
> > Yeah, it is possible to deal with the errors by granting port access permission with the bellow command:
> > $ sudo chown %your username% /dev/wit(the port name you give)
> > Concerning the reason why messages aren't published in the topics, I don't know yet.
> 
> > The launch file use /dev/ttyUSB0 as the dev port, you can check it is correct port.
> > if you use /dev/ttyUSB*, there maybe not problem with the permission of port.
> > you can try again, if not work too, maybe you have to setting the module use the company's software in windows.
> > sorry for so long not response and good luck!
> 
> Hi, I found one reason, and it may be reasonable. The baudrate in the cpp file is 115200 in default. There are three cases, one in "initialization" and another two in the "driver" file with 115200_baudrate. Make sure your sensor is the same or change the code to your setup and catkin_make the code again.

Thank you your idea ! I changed the rate to 115200 on Windows application, the node publish the value in the /imu topic! 
Thank you very much !!! : ) 👍
